
l1 = ['wrapt', 'attrs', 'fsspec', 'MarkupSafe', 'grpcio-status', 'cffi', 'click', 'PyJWT', 'pytz', 'pyasn1', 's3fs', 'yarl', 'psutil', 'tomli', 'isodate', 'jsonschema', 'grpcio', 'soupsieve', 'frozenlist', 'cachetools', 'botocore', 'awscli', 'pyyaml', 'rsa', 's3transfer', 'urllib3', 'setuptools', 'typing-extensions', 'charset-normalizer', 'idna', 'python-dateutil', 'google-api-core', 'cryptography', 'importlib-metadata', 'emoji', 'Flask', 'seaborn', 'NLTK', 'pytest', 'zipp', 'authlib', 'pycparser', 'colorama', 'oauthlib', 'pandas', 'pillow', 'matplotlib', 'scipy', 'boto3', 'cmake', 'nvidia-cuda-nvrtc-cu11', 'jinja2', 'nvidia-cuda-runtime-cu11', 'wheel', 'triton==2.0.0', 'scikit-learn', 'requests', 'Scrapy', 'six', 'opencv-python', 'simplejson', 'opacus', 'redis', 'astropy', 'biopython', 'bokeh', 'dask', 'deap', 'pyspark', 'nilearn', 'networkx', 'SQLAlchemy', 'scikit-image', 'scoop', 'Theano', 'beautifulsoup4', 'Scrapy', 'plotly', 'pycaret', 'mahotas', 'statsmodels']
l2 = ['pyyaml', 'nvidia-cuda-nvrtc-cu11', 'click', 'colorama', 'isodate', 's3fs', 'pycaret', 'tomli', 's3transfer', 'grpcio', 'jsonschema', 'NLTK', 'pytest', 'cryptography', 'cffi', 'wheel', 'pillow', 'pytz', 'nilearn', 'urllib3', 'opencv-python', 'idna', 'nvidia-cuda-runtime-cu11', 'grpcio-status', 'triton==2.0.0', 'cmake', 'Flask', 'boto3', 'wrapt', 'google-api-core', 'importlib-metadata', 'fsspec', 'PyJWT', 'yarl', 'scikit-image', 'beautifulsoup4', 'dask', 'seaborn', 'botocore', 'scikit-learn', 'authlib', 'rsa', 'scoop', 'networkx', 'jinja2', 'Scrapy', 'typing-extensions', 'python-dateutil', 'opacus', 'astropy', 'six', 'pandas', 'SQLAlchemy', 'soupsieve', 'charset-normalizer', 'zipp', 'pycparser', 'attrs', 'requests', 'pyasn1', 'plotly', 'matplotlib', 'deap', 'biopython', 'cachetools', 'frozenlist', 'awscli', 'psutil', 'pyspark', 'bokeh', 'setuptools', 'oauthlib', 'MarkupSafe', 'simplejson', 'emoji', 'Theano', 'redis', 'scipy', 'statsmodels']
print(set(l1).difference(set(l2)))
print(set(l2).difference(set(l1)))
print()


['Flask', 'MarkupSafe', 'NLTK', 'PyJWT', 'SQLAlchemy', 'Scrapy', 'Scrapy', 'Theano', 'astropy', 'attrs', 'authlib', 'awscli', 'beautifulsoup4', 'biopython', 'bokeh', 'boto3', 'botocore', 'cachetools', 'cffi', 'charset-normalizer', 'click', 'cmake', 'colorama', 'cryptography', 'dask', 'deap', 'emoji', 'frozenlist', 'fsspec', 'google-api-core', 'grpcio', 'grpcio-status', 'idna', 'importlib-metadata', 'isodate', 'jinja2', 'jsonschema', 'mahotas', 'matplotlib', 'networkx', 'nilearn', 'nvidia-cuda-nvrtc-cu11', 'nvidia-cuda-runtime-cu11', 'oauthlib', 'opacus', 'opencv-python', 'pandas', 'pillow', 'plotly', 'psutil', 'pyasn1', 'pycaret', 'pycparser', 'pyspark', 'pytest', 'python-dateutil', 'pytz', 'pyyaml', 'redis', 'requests', 'rsa', 's3fs', 's3transfer', 'scikit-image', 'scikit-learn', 'scipy', 'scoop', 'seaborn', 'setuptools', 'simplejson', 'six', 'soupsieve', 'statsmodels', 'tomli', 'triton==2.0.0', 'typing-extensions', 'urllib3', 'wheel', 'wrapt', 'yarl', 'zipp']
['Flask', 'MarkupSafe', 'NLTK', 'PyJWT', 'SQLAlchemy', 'Scrapy', 'Theano', 'astropy', 'attrs', 'authlib', 'awscli', 'beautifulsoup4', 'biopython', 'bokeh', 'boto3', 'botocore', 'cachetools', 'cffi', 'charset-normalizer', 'click', 'cmake', 'colorama', 'cryptography', 'dask', 'deap', 'emoji', 'frozenlist', 'fsspec', 'google-api-core', 'grpcio', 'grpcio-status', 'idna', 'importlib-metadata', 'isodate', 'jinja2', 'jsonschema', 'matplotlib', 'networkx', 'nilearn', 'nvidia-cuda-nvrtc-cu11', 'nvidia-cuda-runtime-cu11', 'oauthlib', 'opacus', 'opencv-python', 'pandas', 'pillow', 'plotly', 'psutil', 'pyasn1', 'pycaret', 'pycparser', 'pyspark', 'pytest', 'python-dateutil', 'pytz', 'pyyaml', 'redis', 'requests', 'rsa', 's3fs', 's3transfer', 'scikit-image', 'scikit-learn', 'scipy', 'scoop', 'seaborn', 'setuptools', 'simplejson', 'six', 'soupsieve', 'statsmodels', 'tomli', 'triton==2.0.0', 'typing-extensions', 'urllib3', 'wheel', 'wrapt', 'yarl', 'zipp']
