apiVersion: apps/v1
kind: Deployment
metadata:
  name: introspected-deployment
  namespace: ai4cloudops-11855c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: introspected
  template:
    metadata:
      labels:
        app: introspected
    spec:
      containers:
        - name: introspected-container
          image: zongshun96/introspected_container:0.01
          imagePullPolicy: "Always"





