kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: snapshot-claim
  namespace: kubeflow 
  labels:
    app: snapshot
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
